In [319]:
import pandas as pd 
from pathlib import Path

In [320]:
project_root = Path.cwd().parent
train_path = project_root / "data" / "raw" / "train.csv"
test_path = project_root/ "data" / "raw" / "test.csv"

In [321]:
df_train = pd.read_csv(train_path)
df_test = pd.read_csv(test_path)

In [322]:
df_train.head()

,Class Index,Title,Description
0,3,Wall St. Bears Claw Back Into the Black (Reuters),"Reuters - Short-sellers, Wall Street's dwindli..."
1,3,Carlyle Looks Toward Commercial Aerospace (Reu...,Reuters - Private investment firm Carlyle Grou...
2,3,Oil and Economy Cloud Stocks' Outlook (Reuters),Reuters - Soaring crude prices plus worries\ab...
3,3,Iraq Halts Oil Exports from Main Southern Pipe...,Reuters - Authorities have halted oil export\f...
4,3,"Oil prices soar to all-time record, posing new...","AFP - Tearaway world oil prices, toppling reco..."

In [323]:
df_test.head()

,Class Index,Title,Description
0,3,Fears for T N pension after talks,Unions representing workers at Turner Newall...
1,4,The Race is On: Second Private Team Sets Launc...,"SPACE.com - TORONTO, Canada -- A second\team o..."
2,4,Ky. Company Wins Grant to Study Peptides (AP),AP - A company founded by a chemistry research...
3,4,Prediction Unit Helps Forecast Wildfires (AP),AP - It's barely dawn when Mike Fitzpatrick st...
4,4,Calif. Aims to Limit Farm-Related Smog (AP),AP - Southern California's smog-fighting agenc...

In [324]:
df_train.shape

(120000, 3)

In [325]:
df_train["Description"][5]

'Reuters - Stocks ended slightly higher on Friday\\but stayed near lows for the year as oil prices surged past  #36;46\\a barrel, offsetting a positive outlook from computer maker\\Dell Inc. (DELL.O)'

In [326]:
df_train["Title"][0]

'Wall St. Bears Claw Back Into the Black (Reuters)'

In [327]:
df_train['source'] = df_train['Title'].str.extract(r'\((.*?)\)')

In [328]:
df_train["source"].isna().sum()

np.int64(102925)

In [329]:
df_train=df_train.drop(["source"],axis=1)

In [330]:
df_train["Title"] = df_train["Title"].str.lower()

In [331]:
df_train["Title"] = df_train['Title'].str.replace(r'\s*\([^)]*\)$', '',regex=True)

In [332]:
df_train["Title"]

0                   wall st. bears claw back into the black
1                 carlyle looks toward commercial aerospace
2                     oil and economy cloud stocks' outlook
3         iraq halts oil exports from main southern pipe...
4         oil prices soar to all-time record, posing new...
                                ...
119995    pakistan's musharraf says won't quit as army c...
119996                    renteria signing a top-shelf deal
119997                      saban not going to dolphins yet
119998                                    today's nfl games
119999                         nets get carter from raptors
Name: Title, Length: 120000, dtype: str

In [333]:
df_train["Description"] = df_train["Description"].str.lower()

In [334]:
df_train["Description"][0]

"reuters - short-sellers, wall street's dwindling\\band of ultra-cynics, are seeing green again."

In [335]:
df_train["Description"] = df_train["Description"].apply(lambda x : x.replace("\\"," "))

In [336]:
df_train["Description"][0]

"reuters - short-sellers, wall street's dwindling band of ultra-cynics, are seeing green again."

In [337]:
df_train['Description'] = df_train['Description'].str.replace(r'^[^-]+-\s*', '', regex=True)

In [338]:
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

In [339]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [340]:
import string 
exclude = string.punctuation

In [341]:
def remove_punc(text):
    for char in exclude:
        text = text.replace(char,'')
    return text

In [342]:
df_train["Description"][2]

'soaring crude prices plus worries about the economy and the outlook for earnings are expected to hang over the stock market next week during the depth of the summer doldrums.'

In [343]:
df_train["Description"]=df_train["Description"].apply(remove_html_tags)
df_train["Description"]=df_train["Description"].apply(remove_url)
df_train["Description"]=df_train["Description"].apply(remove_punc)

In [344]:
df_train["Title"]=df_train["Title"].apply(remove_html_tags)
df_train["Title"]=df_train["Title"].apply(remove_url)
df_train["Title"]=df_train["Title"].apply(remove_punc)

In [345]:
df_train

,Class Index,Title,Description
0,3,wall st bears claw back into the black,shortsellers wall streets dwindling band of ul...
1,3,carlyle looks toward commercial aerospace,private investment firm carlyle group which ha...
2,3,oil and economy cloud stocks outlook,soaring crude prices plus worries about the ec...
3,3,iraq halts oil exports from main southern pipe...,authorities have halted oil export flows from ...
4,3,oil prices soar to alltime record posing new m...,tearaway world oil prices toppling records and...
...,...,...,...
119995,1,pakistans musharraf says wont quit as army chief,pakistani president pervez musharraf has said...
119996,2,renteria signing a topshelf deal,time allstar and twotime gold glover is in the...
119997,2,saban not going to dolphins yet,the miami dolphins will put their courtship of...
119998,2,todays nfl games,1 giants 58 vs spread steelers 1012 giants 58 ...
119999,2,nets get carter from raptors,allstar vince carter was traded by the toront...

In [346]:
df_train["Title"][0]

'wall st bears claw back into the black'

In [347]:
df_train["Description"][0]

'shortsellers wall streets dwindling band of ultracynics are seeing green again'

stop words

In [348]:
from nltk.corpus import stopwords

In [349]:
stopwords.words("English")

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [ ]:
def preprocessor(df):
    df["Title"] = df["Title"].str.lower()
    
    df["Title"] = df['Title'].str.replace(r'\s*\([^)]*\)$', '',regex=True)
    
    df["Description"] = df["Description"].apply(lambda x : x.replace("\\"," "))
    df['Description'] = df['Description'].str.replace(r'^[^-]+-\s*', '', regex=True)
    
    
    df["Description"]=df["Description"].apply(remove_html_tags)
    df["Description"]=df["Description"].apply(remove_url)
    df["Description"]=df["Description"].apply(remove_punc)
    
    df["Title"]=df["Title"].apply(remove_html_tags)
    df["Title"]=df["Title"].apply(remove_url)
    df["Title"]=df["Title"].apply(remove_punc)
    stop_words = set(stopwords.words("english"))
    df_train['Description'] = df_train['Description'].str.split().apply(
    lambda words: " ".join(
    word for word in words
    if word.lower() not in stop_words
    )
    )
    
    df_train['Title'] = df_train['Title'].str.split().apply(
    lambda words: " ".join(
    word for word in words
    if word.lower() not in stop_words
    )
    )   
    df["clean"] = df["Title"] + " " + df["Description"]

In [351]:
train = pd.read_csv(train_path)
test = pd.read_csv(test_path)

In [352]:
preprocessor(train)

In [353]:
train

,Class Index,Title,Description,clean
0,3,wall st bears claw back into the black,Shortsellers Wall Streets dwindling band of ul...,wall st bears claw back into the black Shortse...
1,3,carlyle looks toward commercial aerospace,Private investment firm Carlyle Group which ha...,carlyle looks toward commercial aerospace Priv...
2,3,oil and economy cloud stocks outlook,Soaring crude prices plus worries about the ec...,oil and economy cloud stocks outlook Soaring c...
3,3,iraq halts oil exports from main southern pipe...,Authorities have halted oil export flows from ...,iraq halts oil exports from main southern pipe...
4,3,oil prices soar to alltime record posing new m...,Tearaway world oil prices toppling records and...,oil prices soar to alltime record posing new m...
...,...,...,...,...
119995,1,pakistans musharraf says wont quit as army chief,Pakistani President Pervez Musharraf has said...,pakistans musharraf says wont quit as army chi...
119996,2,renteria signing a topshelf deal,time AllStar and twotime Gold Glover is in the...,renteria signing a topshelf deal time AllStar ...
119997,2,saban not going to dolphins yet,The Miami Dolphins will put their courtship of...,saban not going to dolphins yet The Miami Dolp...
119998,2,todays nfl games,1 Giants 58 Vs spread Steelers 1012 Giants 58 ...,todays nfl games 1 Giants 58 Vs spread Steeler...
119999,2,nets get carter from raptors,AllStar Vince Carter was traded by the Toront...,nets get carter from raptors AllStar Vince Ca...

In [354]:
train  = train.drop(["Title","Description"],axis=1)

In [355]:
preprocessor(test)

In [356]:
test = test.drop(["Title","Description"],axis=1)

In [357]:
train

        Class Index                                              clean
0                 3  wall st bears claw back into the black Shortse...
1                 3  carlyle looks toward commercial aerospace Priv...
2                 3  oil and economy cloud stocks outlook Soaring c...
3                 3  iraq halts oil exports from main southern pipe...
4                 3  oil prices soar to alltime record posing new m...
...             ...                                                ...
119995            1  pakistans musharraf says wont quit as army chi...
119996            2  renteria signing a topshelf deal time AllStar ...
119997            2  saban not going to dolphins yet The Miami Dolp...
119998            2  todays nfl games 1 Giants 58 Vs spread Steeler...
119999            2  nets get carter from raptors  AllStar Vince Ca...

[120000 rows x 2 columns]

In [358]:
test

      Class Index                                              clean
0               3  fears for t n pension after talks Unions repre...
1               4  the race is on second private team sets launch...
2               4  ky company wins grant to study peptides A comp...
3               4  prediction unit helps forecast wildfires Its b...
4               4  calif aims to limit farmrelated smog Southern ...
...           ...                                                ...
7595            1  around the world Ukrainian presidential candid...
7596            2  void is filled with clement  they lost Pedro M...
7597            2  martinez leaves bitter Like Roger Clemens did ...
7598            3  5 of arthritis patients in singapore take bext...
7599            3  ebay gets into rentals EBay plans to buy the a...

[7600 rows x 2 columns]

tokenizer

In [359]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [360]:
vectorizer = TfidfVectorizer(
    stop_words="english", ngram_range=(1, 2),
    max_features=100000, sublinear_tf=True
)

In [361]:
x = train["clean"]
y= train["Class Index"]

In [362]:
x_vec = vectorizer.fit_transform(x)

In [363]:
from sklearn.model_selection import train_test_split

In [364]:
x_train, x_val, y_train, y_val = train_test_split(
    x_vec, y, test_size=0.1, stratify=y, random_state=42
)

# model training :

In [365]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score,classification_report
from sklearn.pipeline import Pipeline

In [366]:
nb_model = MultinomialNB()
nb_model.fit(x_train, y_train)

nb_pred = nb_model.predict(x_val)
print("Naive Bayes validation accuracy:", round(accuracy_score(y_val, nb_pred), 4))

Naive Bayes validation accuracy: 0.9117

In [367]:
x_test = test["clean"]
y_test = test["Class Index"]

In [368]:
x_test_vec = vectorizer.transform(x_test)

In [369]:
y_pred = nb_model.predict(x_test_vec)

In [370]:
print("Test Accuracy:", round(accuracy_score(y_test, y_pred), 4))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Test Accuracy: 0.902

Classification Report:
               precision    recall  f1-score   support

           1       0.91      0.89      0.90      1900
           2       0.95      0.98      0.96      1900
           3       0.87      0.86      0.86      1900
           4       0.88      0.88      0.88      1900

    accuracy                           0.90      7600
   macro avg       0.90      0.90      0.90      7600
weighted avg       0.90      0.90      0.90      7600

In [371]:
svm_model = LinearSVC(C=0.5, random_state=42)
svm_model.fit(x_train, y_train)

svm_pred = svm_model.predict(x_val)
print("Linear SVM validation accuracy:", round(accuracy_score(y_val, svm_pred), 4))

Linear SVM validation accuracy: 0.9195

In [372]:
y_pred = svm_model.predict(x_test_vec)

In [373]:
print("Test Accuracy:", round(accuracy_score(y_test, y_pred), 4))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Test Accuracy: 0.9147

Classification Report:
               precision    recall  f1-score   support

           1       0.94      0.90      0.92      1900
           2       0.95      0.98      0.97      1900
           3       0.88      0.88      0.88      1900
           4       0.89      0.90      0.89      1900

    accuracy                           0.91      7600
   macro avg       0.91      0.91      0.91      7600
weighted avg       0.91      0.91      0.91      7600